---
name: Flake8

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

jobs:
  check:
    name: Check with Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Install Flake8
        shell: bash
        run: |
          set -euo pipefail
          IFS=$'\n\t'
          pipx ensurepath
          pipx install flake8==7.3.0
          if pipx upgrade flake8 | tee -a /dev/stderr | grep -q -e '^upgraded '; then
            exit 1
          fi
      - name: Run Flake8
        shell: bash
        run: |
          set -euo pipefail
          IFS=$'\n\t'
          flake8 *.py
