---
name: Flake8

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

permissions: {}

jobs:
  check:
    name: Check with Flake8
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: Install Flake8
      run: sudo python -m pip install flake8
    - name: Run Flake8
      run: flake8 *.py
