---
name: Flake8

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

permissions: {}

jobs:
  check:
    name: Check with Flake8
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Install Flake8
      run: sudo python -m pip install flake8
    - name: Run Flake8
      run: flake8 *.py
