name: Flake8

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Install Flake8
      run: sudo python -m pip install flake8
    - name: Run Flake8
      run: flake8 *.py
